Fit instead of scale for crops
cloudinary/cloudinary_wordpress pull request #201
Opened 2020-09-11 20:18 UTC by dugajean

2020-09-14 12:05 UTC, DavidCramer requested changes

2020-09-14 12:05 UTC, DavidCramer commented on cloudinary-image-management-and-manipulation-in-the-cloud-cdn/php/class-media.php
> +						'crop'   => $cropped ? 'fill' : 'fit',
@dugajean - it was specified that we use scale for this, so we can't change it. We had a whole ticket on this.
The issue is that the size for the square doesn't have the `cropped` flag.
What we should do is on line 491 don't set the `$crop` as false, but rather check if the dimensions are in ratio.
```
$cropped = ! wp_image_matches_ratio( $meta['width'], $meta['height'], $size['width'], $size['height'] );
```

2020-09-14 13:22 UTC, dugajean commented
@DavidCramer Thanks! Addressed this.

2020-09-15 13:11 UTC, pereirinha approved these changes
@dugajean 

LGTM. I'm happy to see this fixed 👍

2020-09-23 12:41 UTC, DavidCramer approved these changes

2020-10-06 14:44 UTC, merged