add relationship management
cloudinary/cloudinary_wordpress pull request #766
Opened 2022-06-28 11:56 UTC by DavidCramer

2022-06-28 14:23 UTC, DavidCramer commented on php/class-relate.php
> +				$this->media->update_post_meta( $attachment_id, Sync::META_KEYS['transformation'], $meta[ Sync::META_KEYS['transformation'] ] );
@pereirinha right here it should unset the transformations and update the post meta.

2022-06-28 15:54 UTC, pereirinha requested changes
@DavidCramer 

Back to you.

2022-06-28 15:54 UTC, pereirinha commented on php/class-connect.php
> +		return is_wp_error( $status ) ? $status->get_error_message() : $status['status'];
@DavidCramer 

This change will require a change in the docblock for this method, right?

2022-07-06 13:53 UTC, DavidCramer commented
Closing as #773 is cleaner.

2022-07-06 13:53 UTC, closed without merging