Update the readme
cloudinary/cloudinary_wordpress pull request #959
Opened 2024-06-19 15:08 UTC by pereirinha

Updates the readme information for the plugin

## Approach

- n/a

## QA notes

- You can't see these updates before launching them, but you can use the following to validate and preview them:
  - https://wordpress.org/plugins/developers/readme-validator/
  - https://wpreadme.com/

2024-06-19 21:08 UTC, yuval-cloudinary requested changes

2024-06-19 21:08 UTC, yuval-cloudinary commented on readme.txt
>  > Know more on at the [Cloudinary Academy - Introduction to Cloudinary for WordPress Administrators](https://training.cloudinary.com/courses/introduction-to-cloudinary-for-wordpress-administrators-70
Maybe replace "Know more on at the [Cloudinary Academy..." with "Learn more about the plugin with the [Cloudinary Academy..."

2024-06-19 21:08 UTC, yuval-cloudinary commented on readme.txt
>  https://youtu.be/AMVS_O_VEss
I'm not sure what was expected to be here, it takes me to a promotional of Atera.com

2024-06-19 21:08 UTC, yuval-cloudinary commented on readme.txt
> +After deployment, users can access a dashboard that provides insights into  optimization metrics and data usage. The Cloudinary Plugin is based on an architecture that supports any type of site inclu
"into  optimization" has a double space

2024-06-19 21:08 UTC, yuval-cloudinary commented on readme.txt
> +**Optimize your site performance** and user experience by achieving faster page load times and implementing advanced auto-responsive delivery. This not only improves your **Google page rankings** but
"models,  and" has a double space

2024-06-20 08:55 UTC, yuval-cloudinary commented on readme.txt
>  https://youtu.be/AMVS_O_VEss
> I'm not sure what was expected to be here, it takes me to a promotional of Atera.com

that was an ad, and irrelevant for embedded in page

2024-06-21 11:47 UTC, pereirinha commented on readme.txt
> +After deployment, users can access a dashboard that provides insights into  optimization metrics and data usage. The Cloudinary Plugin is based on an architecture that supports any type of site inclu
Good catch

2024-06-23 14:55 UTC, yuval-cloudinary approved these changes

2024-06-26 14:03 UTC, merged